### ISSUE TITLE
Feature request: Dispose the tooltip when clicking outside of it.

### ISSUE THREAD

**Issue by Jackymancs4** [victorhqc/npm-library-description#5]
Hello @victorhqc 
I really like the extension 👍 

I think this is a more suited behavior for a tooltip, allowing for a quick look of the informations and easy access to the links, without having to manually close it.

If you are interested and would like some help, I can work on a PR by the end of the week.

**Comment by victorhqc** [comment]
Thank you! That sounds like a good idea. Makes sense to have it that way. Sure! Feel free to contribute. I'll take it a look when the PR comes 😎
